### ISSUE TITLE
Unable to create new SBOM importer

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#100]
Trying to create a new SBOM importer, the "Create" button stays disabled:

![image](https://github.com/trustification/trustify-ui/assets/202474/c7aa61fe-fb0f-4733-893f-b08ff5a1734a)

To me it looks like I have all required fields added.

**Comment by gildub** [comment]
@ctron, I can see the issue too.
A workaround is to select another Importer type and then select "Sbom" type again.
