### ISSUE TITLE
Information of report not shown

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#102]
Having errors in the report, those are not visible to the user:

![image](https://github.com/trustification/trustify-ui/assets/202474/a44043ee-8f3e-4b06-b5ec-f0e4e80adbd2)

The missing number of items comes from #101 and can be ignored.

**Comment by gildub** [comment]
@ctron, It seems there is a conflict of interest because the current error column displays item.error :

![image](https://github.com/trustification/trustify-ui/assets/1901741/3ec0b867-aea4-434f-8ff1-b130154fd97c)

**Comment by ctron** [comment]
I am not sure that's the case. The error shown in the screenshot is an error fetching any information about the source. That leads to the walker not even known what content would exist. Therefore, the import process fails critically.

The errors shown above, in the original post, are errors on each file, which happened during import. The importer job will record those errors, but as they are permanent errors, will not retry until the file was updated.

**Comment by gildub** [comment]
@ctron, the conflict I see it that the UI currently display data from the `report.error` field.
In the screenshot you provided the data you're expecting are coming from inside `report.report.message` structure.

**Comment by carlosthe19916** [comment]
I am hoping to touch the "Importers" topic with the UX team to understand what exactly we want to see.

**Comment by gildub** [comment]
@ctron, the import-list page currently displaying the `item.error` is here https://github.com/trustification/trustify-ui/blob/main/client/src/app/pages/importer-list/importer-list.tsx#L631
What I'm trying to say is this quite a different structure we get from reports.

**Comment by carlosthe19916** [comment]
There is a log viewer added in https://github.com/trustification/trustify-ui/pull/209 If there is data on items.report.messages
