### ISSUE TITLE
Order of reports seems random

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#104]
Taking a look at the order of the reports in the importer section, the order seems completely random. The API however seems to work.

![image](https://github.com/trustification/trustify-ui/assets/202474/c99fbde9-a009-43a8-93cc-da098d571128)

**Comment by gildub** [comment]
@ctron, this is effectively occurring after the API request as react-query is providing the records in the right order.

Investigation shows the reports order is modified, randomly, within `useLocaTableControls` hook due to `getSortValues` over `startDate` and `endDate`.
