### ISSUE TITLE
Generate the Client and models from the openapi spec

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify-ui#119]
As UI developers and Backend developers are working separately it would be good relying on the openapi spec to generate the models and/or the client for communicating with the backend.

Here is a tool that might help https://github.com/hey-api/openapi-ts

This is a proposal and should be properly evaluated to consider if it makes things easier. If it increases complexity then no.

**Comment by chirino** [comment]
The generator likely won't be able to generate anything nice until we fix the generated openapi spec a bit.  It likely depends on https://github.com/trustification/trustify/issues/580 being fixed first.

**Comment by carlosthe19916** [comment]
This has been done already some time ago, I don't recall the exact PR though. Closing this issue as it has been completed
