### ISSUE TITLE
Sort importer runs by newest first

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#147]
Taking a look at the importer runs, I see older ones first. I would expect that the newer ones get shown first.

**Comment by carlosthe19916** [comment]
Fixed by https://github.com/trustification/trustify-ui/pull/230

![Screenshot From 2024-11-19 10-24-38](https://github.com/user-attachments/assets/9a02f314-54c0-45bd-8dea-cd7dd1fb42f2)
