### ISSUE TITLE
Product details view doesn't seem to make sense

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#150]
This is the product details view of the `ubi8-container`:

![image](https://github.com/user-attachments/assets/313794e9-a5bb-4f54-b184-585380ff7ee3)

* Most fields are empty
* The version comes last, despite the tab being called "Versions"
* I would expect to be able to click on something to that to SBOMs

**Comment by carlosthe19916** [comment]
Currently we do not have products any longer. There are plans to introduce that concept in the future but the current UI does not have it yet.

Closing this issue. When the time for the UI comes to have Products we can create more issues.
