### ISSUE TITLE
SBOM List - V1 Parity 

### ISSUE THREAD

**Issue by PhilipCattanach** [trustification/trustify-ui#155]
Complete the implementation of the SBOM List screen to sufficient equivalence with version 1.
Ensure that all changes in terms of fields, actions and labels have been agreed with UXD and Product Management.
Use [this sheet](https://docs.google.com/spreadsheets/d/1mhBd3-UYvSANIXwRPDrCdGplN7cq5rQPJhIywo5mcDY/edit?gid=1088076328#gid=1088076328) as a vehicle for agreeing the new collections of fields, labels and actions.

**Comment by PhilipCattanach** [comment]
@carlosthe19916 - I have moved the UI related labels into the trustify-ui repo. And closed 803 and created the same issue here.

**Comment by carlosthe19916** [comment]
After trying to implement this I faced limitations with the data available in the rest endpoints and those things need to be discussed globally with the team. Here is the document that describes what are the issues that need to be addressed to be able to complete this task [data limitations](https://docs.google.com/document/d/1PDTyvNlbzofq3_WaVFTkZY9JfGV4gz0qjctXhcPYfdw/edit?usp=sharing)
