### ISSUE TITLE
Can't select text enclosed in blue boxes

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify-ui#156]
On a page like http://localhost:8080/packages/8c4d77eb-2dab-51b0-9528-102a58328464 where affected Vulnerabilities and SBOM's are listed as what appears to be "buttons", I'm unable to select/copy the text within those buttons. Nor can I select the text comprising the links that are shown in the sidebar when I click one of the buttons.

I was trying to text someone the name of an affected SBOM, and I found that I couldn't do it with my mouse from that page. Not very convenient or user-friendly.

**Comment by carlosthe19916** [comment]
In light of the V1 work parity for the UI. The Package Details page was fully replaced by exactly the look and feel of V1 UI so we no longer have the BLUE BOXES.

Closing this issue as the whole page does not exist any more. We can keep creating new issues for the new Package Details Page.

![image](https://github.com/user-attachments/assets/f813caf5-06f3-45da-92fc-038db3010686)
