### ISSUE TITLE
crate always gets built with --dev

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#16]
It looks to me like the crate always builds the JS part with `--dev`. For a Rust release build, I would also expect a release build of the JS part.

**Comment by helio-frota** [comment]
Also, in Containerfile you shared, it makes a reference to `dev` -> `RUN npm run build --dev` but things are built with `prod`

**Comment by carlosthe19916** [comment]
I think there is a misunderstanding that was introduced the moment the Rust Crate was created in this repo.
- The Rust crate in this repo is executing `npm run build --dev`. Which suggests that there is a "dev" and a "prod" way of building. That is not true; when the UI is build it is always built in "prod" mode, there is no "dev" build mode.

So, the short answer is: it is expected to build the UI always in Prod mode. For dev mode we have to start the server using `npm run start:dev`

I will create a PR to remove current `--dev` param from the Rust create as it is a parameter that is never used

**Comment by helio-frota** [comment]
@carlosthe19916 thanks for the extra info!

**Comment by carlosthe19916** [comment]
The UI, once built, it is done in prod mode. Those files will be served on the trustify repository through https://github.com/trustification/trustify-ui/pull/32
