### ISSUE TITLE
Advisory source doesn't seem to be the actual source

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#183]
Opening the source tab, I see this:

![image](https://github.com/user-attachments/assets/e5849363-18e9-4a2b-baa4-affc97ba58ab)

It looks like some dump of the request/response. But not the actual advisory data.

**Comment by carlosthe19916** [comment]
In light of UI V1 parity, the Source viewer was removed as https://trust.rhcloud.com/ does not include any Source Viewer.

Closing this issue as the page with the issue does no longer exists.
We can reopen this issue or create a new one if the decision will be to include the Source Viewer in a future release
