### ISSUE TITLE
Review - investigate - fix inconsistencies with ENVs (prod/dev) 

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify-ui#19]
Related to https://github.com/trustification/trustify-ui/issues/16#issuecomment-2117332531

When using the Containerfile shared by Jens, I also noticed that 

`RUN npm run build --dev` runs `production` build `"build": "NODE_ENV=production webpack --config ./config/webpack.prod.ts",`

**Comment by carlosthe19916** [comment]
Yes, the UI build phase is always done in production mode and it the expected behavior. I explained it here https://github.com/trustification/trustify-ui/issues/16#issuecomment-2117398954
