### ISSUE TITLE
CVE Detail Page

### ISSUE THREAD

**Issue by kahboom** [trustification/trustify-ui#190]
Implement the CVE detail page

## To Do

- [x] Update overview details for CVE
- [x] `Reserved` property
- [x] Issue with tabs and background not matching
- [x] Remove search bar
- [x] CSS: fix spacing of properties in overview
- [x] Description
- [x] Update tabs for Related Products -> Related CVEs
- [x] ~~Remove Related Advisories tab~~
- [x] ~~Download button~~
- [x] Update column names for Related SBOMs
  - [x] Name
  - [x] Version
  - [x] Status
  - [x] Dependencies
  - [x] Supplier
  - [x] Created on
- [x] Update column names for Related Advisories
  - [x] Revision
  - [x] Vulnerabilities
  - [x] No aggregate severity showing up in column value?
- [x] Aesthetic enhancements (alignment of badge + title, etc.)

**Comment by kahboom** [comment]
@carlosthe19916 are we getting PM to sign off on each page before closing, or can this be closed?

**Comment by carlosthe19916** [comment]
@kahboom let's close it and whenever we find things to fix we can open an issue for specific things.

**Comment by kahboom** [comment]
completed via https://github.com/trustification/trustify-ui/pull/211
