### ISSUE TITLE
Investigate --> Update all the dependencies

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify-ui#20]
> [!WARNING]  
> Currently this is not possible, some things stops to compile.
> Build get broken as well
> We need to do it before the repo get bigger

> [!CAUTION]
> Need to find a way to keep things working on the business part

**Comment by carlosthe19916** [comment]
Just like the warning message describes: `Currently this is not possible, some things stops to compile.`. "Update all the dependencies" means introducing version of dependencies that might or might not have breaking changes, therefore npm is clear enough to warn us not to do it.

To have the latest version of each dependency adds no value to the app unless there are vulnerabilities identified. I would suggest keep updating dependencies as soon as we need them but not blindly update them all.

**Comment by helio-frota** [comment]
> but not blindly update them all

Don't worry I wrote the warning messages exactly because this is not current possible do it. :+1:

**Comment by helio-frota** [comment]
closing in the light of https://github.com/trustification/trustify-ui/pull/26#pullrequestreview-2066013040
