### ISSUE TITLE
Unable to view advisories

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#225]
There seems to be no way to view advisories. The menu entry on the left hand side is gone and navigating (through vulnerabilities) to the advisories details page leaves an empty main area:

![image](https://github.com/user-attachments/assets/c83e5e0f-8b24-4190-bc3e-8f712b0b3709)

**Comment by carlosthe19916** [comment]
Duplicate of https://github.com/trustification/trustify-ui/issues/214
