### ISSUE TITLE
Vulnerabilities List Page: Related documents column

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify-ui#235]
Currently we are rendering an "X" into that column.

We need to render the number of SBOMS affected by the Vulnerability

**Comment by kahboom** [comment]
This should be done already through #229 , however, I am not able to get sample data to show a meaningful value in the UI:

![Screenshot 2024-11-13 at 11 02 43 AM](https://github.com/user-attachments/assets/53e9618d-1c88-4c67-9ee8-efed9ca6ff85)

![Screenshot 2024-11-13 at 11 06 00 AM](https://github.com/user-attachments/assets/343450c1-65ce-455b-85f0-db7c8981e41b)

And when I try to sort by "Related documents" I'm getting an error in the browser console about the column name being invalid, so I'll have to check that out:

![Screenshot 2024-11-13 at 11 08 33 AM](https://github.com/user-attachments/assets/c562efaa-3a52-4e27-940c-c3cfc613d134)

**Comment by carlosthe19916** [comment]
@kahboom I missed https://github.com/trustification/trustify-ui/pull/229 sorry.

But:

- Since in V1 that column is not sortable perhaps we can just remove the sorting feature of that column to avoid issues
- The "Related Documents" columns is quite ambiguous in V1.
  - Let's ask PM to verify what exactly she expects to see in that column. The current code is rendering the count of CWEs but I am thinking that perhaps it should render the number of SBOMs affected by that Vulnerability and not CWEs. We'll need to confirm it
