### ISSUE TITLE
Advisory drawer goes blank

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#256]
I don't know how to reproduce it. But it looks like this:

![image](https://github.com/user-attachments/assets/e4188505-0ad3-48b4-b641-90c802e22774)

Might have something to do with moving away from the window.

**Comment by ctron** [comment]
In a case like this, it's not possible to close the drawer.

**Comment by carlosthe19916** [comment]
@ctron From the screenshot you shared, I can tell that it is not the latest version of the UI. Please use the latest version

**Comment by ctron** [comment]
Is that fixed in the latest version?

**Comment by carlosthe19916** [comment]
The latest version does not even have a Drawer.
Again, please use always the latest version for reporting issues

**Comment by ctron** [comment]
I didn't expect a change like that after having merged the finished UI last week.
