### ISSUE TITLE
Vulnerabilities tab on http://localhost:3000/sboms/{id} page does not filter CVEs

### ISSUE THREAD

**Issue by dejanb** [trustification/trustify-ui#270]
After the performance improvement done to the API, the tab shows multiple entries for the same CVE (some with all packages).

<img width="3109" alt="image" src="https://github.com/user-attachments/assets/d5871933-e607-42d9-b7e5-eefff6f42cad">

**Comment by carlosthe19916** [comment]
@dejanb I think this was fixed by https://github.com/trustification/trustify-ui/pull/266 . Just some minutes ago. Could you confirm that issue is gone? But somehow you will need to use the latest version of the ui

**Comment by carlosthe19916** [comment]
@dejanb confirmed the issue is gone. Closing this issue.
If the issue was not fixed we can reopen this or create a new one
