### ISSUE TITLE
OIDC handshake seems broken

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#35]
![image](https://github.com/trustification/trustify-ui/assets/202474/68a26c34-b6ea-4ff7-8e13-2f81e28d0e47)

1. The application loads
2. It discovers the OIDC configuration
3. It redirects to the OIDC issuer
4. The issuer redirects back to the UI (including the code)
5. The UI exchanges the code for a token
6. 🔥 The UI redirects to the OIDC issuer again, including the redirect information (code) received in 4.

**Comment by carlosthe19916** [comment]
This might be related to https://github.com/trustification/trustify-ui/issues/34#issuecomment-2126837085
- This issue appeared while using the UI with a customized oidc provider
- I'll wait for https://github.com/trustification/trustify-ui/issues/34 to be solved before investigating this issue, as the problem might not be the UI but the customized oidc provider

**Comment by ctron** [comment]
I can reproduce the issue exactly the same with your PR. I think you can reproduce this yourself by:

1. starting podman compose
2. starting the server
3. killing the keycloak pod
4. access the UI

**Comment by ctron** [comment]
You will also need to remove the line `.default_authenticator(self.authenticator)` in the `run` function of `server/src/lib.rs`.

**Comment by ctron** [comment]
So I can see that it behaves differently. The question now is: why?

**Comment by carlosthe19916** [comment]
My expectation is that if we were able to fully solve https://github.com/trustification/trustify-ui/issues/34 and the conclusions made there; then, this problem will also be gone.

Let's attack one problem at a time, which is https://github.com/trustification/trustify-ui/issues/34

**Comment by ctron** [comment]
I think the actual problem is here. Issue #34 is more a cache issue. Maybe a browser issue because of that infinite loop. I wouldn't want to waste any cycles in this issue. Because there's a way to "fix" it by reloading in a new tab.

**Comment by carlosthe19916** [comment]
> I think the actual problem is here. Issue #34 is more a cache issue. Maybe a browser issue because of that infinite loop. I wouldn't want to waste any cycles in this issue. Because there's a way to "fix" it by reloading in a new tab.

Seems like this issue has been solved and not relevant any more.
Closing this issue. If the problem persists we can reopen this issue or create a new issue.
