### ISSUE TITLE
Invalid data in the importer UI

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#39]
![image](https://github.com/trustification/trustify-ui/assets/202474/12a9c5be-b201-4233-8769-a7aa16b25f45)

It looks like as if the importer UI has some issues showing data.

* Enable is actually disabled
* source is present but now shown
* Duration is 300s, but shown as 60s
* The type is `osv`

As the `osv` type is new, it might make sense to gracefully handle cases like this and either refuse to edit an unknown type (with a user-friendly error message). Or show the string value and only the common data. Which still might be tricky to edit in this case.

**Comment by carlosthe19916** [comment]
This also should've been resolved by https://github.com/trustification/trustify-ui/pull/44 . There were new types of importers that were introduced and the UI was not handling them. But that is fixed.

Closing this issue, and if we discover it has not been fully fixed, we can reopen this one
