### ISSUE TITLE
Investigate the possibility of having just one `tsconfig.json` file

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify-ui#5]
```console
➜  frontend fd tsconfig
client/tsconfig.json
common/tsconfig.json
```

**Comment by helio-frota** [comment]
Still not 100% clear to me (due my front-end ignorance) but the presence of two bundlers (webpack and rollup) + using `npm workspaces` where one `workspace-package` is not a TS project can make things more harder.

```console
├── client  (react - TS + webpack)
├── common (TS + rollup)
└── server  (express - JS + rollup)
```

**Comment by carlosthe19916** [comment]
Having multiple tsconfig.json files do not represent a bug or an issue. Unifying them won't solve any problem.
Closing this ticket until we know this is a problem.
