### ISSUE TITLE
Not showing the package qualifiers is confusing

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#64]
Having a set of packages which only differ by qualifiers is currently quite confusing to me:

![image](https://github.com/trustification/trustify-ui/assets/202474/2adf574e-9969-4273-82b3-64a88e29b18a)

Only one you expand the row the information is present:

![image](https://github.com/trustification/trustify-ui/assets/202474/1b35ba89-7460-45b2-9d30-645b0dbac902)

However, that consumes quite some space and doesn't look well arranged to me.

**Comment by carlosthe19916** [comment]
Showing everything in the same row is a challenge as there is limited space.

 Would it be reasonable to move the qualifiers to the main row (as you are suggesting) but move the `namespace` and `path` to the expanded area? I am asking, to understand whether or not without the namespace and path being showed at first, we could avoid confusion between packages?
