### ISSUE TITLE
Bring back the code editor/viewer

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#73]
SPoG UI has the embedded code viewer for directly viewing documents (like SBOMs, …). This is a super handy feature when trying to understand why the data in the UI is as it is, because one can take a direct look at the source.

I agree that it might not be that useful for the average user, but for the more advanced users it sure is.

**Comment by carlosthe19916** [comment]
Closing this issue as we are working towards V1 parity and https://trust.rhcloud.com/ does not include any Source Viewer.

If in the future that changes we can reopen this issue or create a new one
