### ISSUE TITLE
Advisories list is confusing

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#87]
The Vulnerabilities -> Advisories (Tab) feels confusing:

![image](https://github.com/trustification/trustify-ui/assets/202474/e7088084-e861-496a-9f5d-7d55ef020625)

I see two advisories, with the same ID as the vulnerability. With different information.

Now I do know exactly why it has the same ID and different information. However, we should explain to the user that situation.

One way to deal with this could be to show the "source" of that information. We could e.g. add two badges: a type, and a source. Like `type=cve`, and `type=csaf, source=redhat.com`.

**Comment by carlosthe19916** [comment]
Sounds like a good idea. We just don't have `type` nor `source` fields on each Vulnerability yet. But once they are available, that would be useful, I agree

**Comment by gildub** [comment]
@ctron, could you please explain why several vulnerabilities with same ID do exist ?

**Comment by ctron** [comment]
The ID isn't a system generated ID. But a user (document provider) provided piece of information. Naming an advisory after the CVE it describes seems a common pattern.
